# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_user_confirm_pw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(max_length=256),
        ),
    ]
