# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20170125_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
